var usersData = [
    /*******************************refgyieufjoxkoerijhygyhuijop[oijuhyg*************************] */
    { 'name': 'Ayesha Chopra', 'gender': 'female', 'interests': ['Documentaries', 'Basketball', 'Video Games', 'Yoga', 'Cultural Exploration', 'Board Games', 'Card Games', 'Digital Art', 'Trail Hiking', 'Non-Fiction', 'Pottery', 'Italian Cuisine', 'Solo Travel', 'Fingerstyle', 'Salsa Dancing', 'Gourmet Cooking', 'Backpacking', 'Acoustic', 'Nature Walks', 'Swing Dance'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Neha Verma', 'gender': 'female', 'interests': ['Digital Art', 'Asian Fusion', 'Trail Hiking', 'Solo Travel', 'Backpacking', 'Golf', 'Backpacking', 'Action Movies', 'Science Fiction', 'Day Hikes', 'Ballet', 'Gourmet Cooking', 'Documentaries', 'Painting', 'Romantic Comedies', 'Sculpture', 'Yoga', 'Electric', 'Swing Dance', 'Road Trips'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Riya Choudhury', 'gender': 'female', 'interests': ['Tennis', 'Board Games', 'Pottery', 'Adventure', 'Classic Films', 'Soccer', 'Non-Veg', 'Golf', 'Documentaries', 'Non-Smoker', 'Video Games', 'Trail Hiking', 'Running Training', 'Fantasy', 'Ballet', 'Youth Mentorship', 'Swimming', 'Backpacking', 'Mobile Games', 'Asian Fusion'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Sanya Kapoor', 'gender': 'female', 'interests': ['Romantic Comedies', 'Fiction Novels', 'Nature Walks', 'Classical', 'Painting', 'Swimming', 'Golf', 'Card Games', 'Board Games', 'Mobile Games', 'Fingerstyle', 'Weightlifting', 'Salsa Dancing', 'Documentaries', 'Acoustic', 'CrossFit', 'Non-Fiction', 'Animal Shelter Volunteering', 'Backpacking', 'Sci-Fi Series'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Kiara Reddy', 'gender': 'female', 'interests': ['Swimming', 'Trail Hiking', 'Electric', 'Painting', 'Classical', 'Card Games', 'Mystery and Thrillers', 'Soccer', 'Romantic Comedies', 'Fiction Novels', 'French Cuisine', 'Asian Fusion', 'Road Trips', 'CrossFit', 'Fingerstyle', 'Foodie', 'Ballroom Dancing', 'Bass', 'Cultural Exploration', 'Sculpture'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Aditi Malhotra', 'gender': 'female', 'interests': ['Disaster Relief', 'Sci-Fi Series', 'Salsa Dancing', 'Yoga', 'Mystery and Thrillers', 'Italian Cuisine', 'Road Trips', 'Cultural Exploration', 'Fingerstyle', 'Electric', 'Basketball', 'Photography', 'Non-Smoker', 'Soccer', 'Nature Walks', 'Fantasy', 'Foodie', 'Fiction Novels', 'Science Fiction', 'Non-Fiction'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Tara Bhat', 'gender': 'female', 'interests': ['Board Games', 'Mystery and Thrillers', 'Disaster Relief', 'Non-Fiction', 'Swimming', 'Non-Smoker', 'Fingerstyle', 'Cultural Exploration', 'Golf', 'Classic Films', 'Ballroom Dancing', 'Nature Walks', 'Soccer', 'Classical', 'Animal Shelter Volunteering', 'Gourmet Cooking', 'Trail Hiking', 'Science Fiction', 'French Cuisine', 'Mobile Games'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Diya Sharma', 'gender': 'female', 'interests': ['Golf', 'Disaster Relief', 'Hip-Hop Dance', 'Tennis', 'Trail Hiking', 'Backpacking', 'Non-Smoker', 'Mystery and Thrillers', 'Salsa Dancing', 'Environmental Conservation', 'Classic Films', 'Card Games', 'Weightlifting', 'Road Trips', 'Soccer', 'Adventure', 'Science Fiction', 'Romantic Comedies', 'Sculpture', 'Mountain Climbing'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Khushi Khanna', 'gender': 'female', 'interests': ['Ballet', 'Non-Smoker', 'Pottery', 'Day Hikes', 'Disaster Relief', 'Nature Walks', 'Action Movies', 'Animal Shelter Volunteering', 'Basketball', 'Sculpture', 'Mobile Games', 'Classic Films', 'Painting', 'Asian Fusion', 'Trail Hiking', 'Acoustic', 'Non-Fiction', 'Romantic Comedies', 'Cultural Exploration', 'Mystery and Thrillers'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Aarohi Nair', 'gender': 'female', 'interests': ['Animal Shelter Volunteering', 'Adventure Travel', 'Pottery', 'Board Games', 'Salsa Dancing', 'Foodie', 'Role-Playing Games (RPGs)', 'Soccer', 'Mystery and Thrillers', 'Action Movies', 'Weightlifting', 'Backpacking', 'Day Hikes', 'Running Training', 'Swimming', 'Solo Travel', 'Fingerstyle', 'Painting', 'Romantic Comedies', 'Pilates'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Avani Singh', 'gender': 'female', 'interests': ['Acoustic', 'Environmental Conservation', 'Fiction Novels', 'Non-Veg', 'Card Games', 'Hip-Hop Dance', 'Ballroom Dancing', 'Non-Smoker', 'Road Trips', 'Salsa Dancing', 'Backpacking', 'Animal Shelter Volunteering', 'Solo Travel', 'Youth Mentorship', 'Role-Playing Games (RPGs)', 'Foodie', 'Disaster Relief', 'Sci-Fi Series', 'Digital Art', 'Adventure Travel'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Sara Sethi', 'gender': 'female', 'interests': ['Non-Fiction', 'Bass', 'Backpacking', 'Card Games', 'Asian Fusion', 'Day Hikes', 'Nature Walks', 'Classic Films', 'Photography', 'Cultural Exploration', 'Non-Smoker', 'Salsa Dancing', 'Non-Veg', 'Animal Shelter Volunteering', 'Golf', 'Yoga', 'Baking Pastries', 'Weightlifting', 'Classical', 'Electric'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Nandini Shah', 'gender': 'female', 'interests': ['Classic Films', 'Youth Mentorship', 'Bass', 'Environmental Conservation', 'Card Games', 'Road Trips', 'Nature Walks', 'Mystery and Thrillers', 'Electric', 'Painting', 'Non-Smoker', 'Classical', 'Non-Fiction', 'Adventure', 'Backpacking', 'Trail Hiking', 'Mobile Games', 'Ballroom Dancing', 'Yoga', 'Video Games'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Esha Gupta', 'gender': 'female', 'interests': ['Digital Art', 'Photography', 'Sci-Fi Series', 'Animal Shelter Volunteering', 'Nature Walks', 'Non-Smoker', 'Non-Fiction', 'Disaster Relief', 'Backpacking', 'Youth Mentorship', 'Board Games', 'Pottery', 'Soccer', 'Swimming', 'Mountain Climbing', 'Sculpture', 'Road Trips', 'Italian Cuisine', 'Foodie', 'Romantic Comedies'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Priya Sharma', 'gender': 'female', 'interests': ['Romantic Comedies', 'Photography', 'Fingerstyle', 'Action Movies', 'Gourmet Cooking', 'Running Training', 'Day Hikes', 'Swimming', 'Role-Playing Games (RPGs)', 'Solo Travel', 'Documentaries', 'Adventure Travel', 'Painting', 'Basketball', 'Swing Dance', 'Foodie', 'Yoga', 'Classic Films', 'Pilates', 'Video Games'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Priya Sharma', 'gender': 'female', 'interests': ['Fantasy', 'Mountain Climbing', 'Yoga', 'Swimming', 'Pottery', 'Animal Shelter Volunteering', 'Photography', 'Sci-Fi Series', 'Running Training', 'Acoustic', 'Sculpture', 'Documentaries', 'Action Movies', 'Painting', 'Ballroom Dancing', 'Cultural Exploration', 'Tennis', 'Baking Pastries', 'Fingerstyle', 'CrossFit'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Aisha Patel', 'gender': 'female', 'interests': ['Action Movies', 'Nature Walks', 'Swimming', 'Science Fiction', 'Ballet', 'CrossFit', 'Mobile Games', 'Animal Shelter Volunteering', 'Road Trips', 'Sci-Fi Series', 'Digital Art', 'Mystery and Thrillers', 'Disaster Relief', 'French Cuisine', 'Running Training', 'Tennis', 'Backpacking', 'Yoga', 'Card Games', 'Gourmet Cooking'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Khushi Khanna', 'gender': 'female', 'interests': ['Disaster Relief', 'CrossFit', 'Pottery', 'Italian Cuisine', 'Acoustic', 'Ballroom Dancing', 'Solo Travel', 'Youth Mentorship', 'Digital Art', 'Golf', 'Weightlifting', 'Cultural Exploration', 'Ballet', 'Tennis', 'Animal Shelter Volunteering', 'Mobile Games', 'Baking Pastries', 'Bass', 'Environmental Conservation', 'Salsa Dancing'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Pari Yadav', 'gender': 'female', 'interests': ['Trail Hiking', 'Hip-Hop Dance', 'Foodie', 'Mystery and Thrillers', 'Adventure Travel', 'Swimming', 'Yoga', 'Fantasy', 'Italian Cuisine', 'Electric', 'Digital Art', 'Youth Mentorship', 'Backpacking', 'Sculpture', 'Role-Playing Games (RPGs)', 'Adventure', 'Sci-Fi Series', 'Homeless Shelter Support', 'Fingerstyle', 'Non-Veg'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Esha Gupta', 'gender': 'female', 'interests': ['Ballet', 'Board Games', 'Action Movies', 'Pilates', 'Day Hikes', 'Non-Veg', 'Digital Art', 'Running Training', 'Disaster Relief', 'Environmental Conservation', 'Swing Dance', 'Photography', 'Fantasy', 'Pottery', 'Baking Pastries', 'Homeless Shelter Support', 'Video Games', 'Weightlifting', 'Card Games', 'Adventure Travel'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Riya Aggarwal', 'gender': 'female', 'interests': ['Gourmet Cooking', 'Golf', 'Tennis', 'Fiction Novels', 'Nature Walks', 'Role-Playing Games (RPGs)', 'Italian Cuisine', 'Day Hikes', 'Documentaries', 'Painting', 'Romantic Comedies', 'Homeless Shelter Support', 'Running Training', 'Fingerstyle', 'Basketball', 'Yoga', 'Disaster Relief', 'Photography', 'Environmental Conservation', 'Foodie'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Sanya Kapoor', 'gender': 'female', 'interests': ['Nature Walks', 'Classical', 'CrossFit', 'Card Games', 'Fingerstyle', 'Painting', 'Swing Dance', 'Pilates', 'Baking Pastries', 'Road Trips', 'Italian Cuisine', 'Solo Travel', 'Backpacking', 'Role-Playing Games (RPGs)', 'Swimming', 'Bass', 'Day Hikes', 'Board Games', 'Youth Mentorship', 'Adventure Travel'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Avani Singh', 'gender': 'female', 'interests': ['Adventure', 'Bass', 'Video Games', 'Pilates', 'Day Hikes', 'French Cuisine', 'Weightlifting', 'Non-Veg', 'Road Trips', 'Board Games', 'Mountain Climbing', 'Backpacking', 'Classic Films', 'Romantic Comedies', 'Ballet', 'Backpacking', 'Environmental Conservation', 'Salsa Dancing', 'Fingerstyle', 'Acoustic'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Meher Khatri', 'gender': 'female', 'interests': ['Card Games', 'Nature Walks', 'Italian Cuisine', 'Board Games', 'Soccer', 'Mobile Games', 'Acoustic', 'French Cuisine', 'Ballet', 'Weightlifting', 'Ballroom Dancing', 'Backpacking', 'Digital Art', 'Romantic Comedies', 'Documentaries', 'Day Hikes', 'Fingerstyle', 'Baking Pastries', 'Swimming', 'Animal Shelter Volunteering'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Ayesha Chopra', 'gender': 'female', 'interests': ['Running Training', 'Action Movies', 'Soccer', 'Science Fiction', 'Golf', 'Swing Dance', 'Day Hikes', 'Trail Hiking', 'Fingerstyle', 'CrossFit', 'Italian Cuisine', 'Pottery', 'Salsa Dancing', 'Sci-Fi Series', 'Non-Veg', 'Cultural Exploration', 'Fantasy', 'Video Games', 'Documentaries', 'Classical'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Alia Suri', 'gender': 'female', 'interests': ['Cultural Exploration', 'CrossFit', 'Nature Walks', 'Salsa Dancing', 'Mountain Climbing', 'Fiction Novels', 'Adventure', 'Video Games', 'Non-Fiction', 'Solo Travel', 'Non-Smoker', 'Golf', 'Bass', 'Trail Hiking', 'Pilates', 'Environmental Conservation', 'Acoustic', 'Backpacking', 'Gourmet Cooking', 'Mobile Games'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Neha Verma', 'gender': 'female', 'interests': ['Road Trips', 'Environmental Conservation', 'Sculpture', 'Basketball', 'Fiction Novels', 'Nature Walks', 'Italian Cuisine', 'Trail Hiking', 'Bass', 'Day Hikes', 'Pottery', 'Hip-Hop Dance', 'Youth Mentorship', 'Acoustic', 'Classic Films', 'Pilates', 'Baking Pastries', 'Backpacking', 'Painting', 'Electric'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Tara Bhat', 'gender': 'female', 'interests': ['Environmental Conservation', 'Soccer', 'Road Trips', 'Acoustic', 'Ballroom Dancing', 'Fiction Novels', 'Yoga', 'Bass', 'Ballet', 'Backpacking', 'Role-Playing Games (RPGs)', 'Backpacking', 'Electric', 'Foodie', 'French Cuisine', 'Homeless Shelter Support', 'Classic Films', 'Solo Travel', 'Adventure Travel', 'Pottery'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Riya Choudhury', 'gender': 'female', 'interests': ['Backpacking', 'Ballroom Dancing', 'Gourmet Cooking', 'Pilates', 'Backpacking', 'Italian Cuisine', 'Salsa Dancing', 'Road Trips', 'Swimming', 'Fiction Novels', 'Adventure Travel', 'Documentaries', 'Animal Shelter Volunteering', 'Youth Mentorship', 'Bass', 'French Cuisine', 'Day Hikes', 'Weightlifting', 'Video Games', 'Hip-Hop Dance'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },


    { 'name': 'Rajat Kapoor', 'gender': 'male', 'interests': ['Trail Hiking', 'Mountain Climbing', 'Sci-Fi Series', 'Tennis', 'Video Games', 'Nature Walks', 'Digital Art', 'Role-Playing Games (RPGs)', 'Disaster Relief', 'Acoustic', 'Fantasy', 'Cultural Exploration', 'Non-Fiction', 'Yoga', 'Gourmet Cooking', 'Foodie', 'Adventure Travel', 'Non-Smoker', 'Fingerstyle', 'Solo Travel'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Kabir Rao', 'gender': 'male', 'interests': ['Ballroom Dancing', 'Gourmet Cooking', 'Backpacking', 'Ballet', 'Tennis', 'Electric', 'Swimming', 'Sci-Fi Series', 'Acoustic', 'Mobile Games', 'Disaster Relief', 'Adventure Travel', 'Role-Playing Games (RPGs)', 'Golf', 'Trail Hiking', 'Science Fiction', 'Solo Travel', 'Board Games', 'Day Hikes', 'Documentaries'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Dhruv Suri', 'gender': 'male', 'interests': ['Documentaries', 'Animal Shelter Volunteering', 'Non-Smoker', 'Cultural Exploration', 'Fingerstyle', 'Solo Travel', 'Electric', 'Romantic Comedies', 'French Cuisine', 'Adventure', 'Road Trips', 'Gourmet Cooking', 'Foodie', 'CrossFit', 'Non-Fiction', 'Bass', 'Weightlifting', 'Action Movies', 'Golf', 'Trail Hiking'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Sameer Joshi', 'gender': 'male', 'interests': ['Trail Hiking', 'Animal Shelter Volunteering', 'Ballroom Dancing', 'Classical', 'Road Trips', 'CrossFit', 'Role-Playing Games (RPGs)', 'Adventure', 'Golf', 'Science Fiction', 'Running Training', 'Action Movies', 'Acoustic', 'Non-Veg', 'Romantic Comedies', 'Ballet', 'Sci-Fi Series', 'Photography', 'Asian Fusion', 'Italian Cuisine'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Aarav Patel', 'gender': 'male', 'interests': ['Trail Hiking', 'Animal Shelter Volunteering', 'Gourmet Cooking', 'Mobile Games', 'Asian Fusion', 'Baking Pastries', 'Non-Smoker', 'Pilates', 'Sculpture', 'Role-Playing Games (RPGs)', 'Adventure Travel', 'CrossFit', 'Classic Films', 'Non-Veg', 'Video Games', 'Fiction Novels', 'Weightlifting', 'Board Games', 'Ballroom Dancing', 'Homeless Shelter Support'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Pranav Yadav', 'gender': 'male', 'interests': ['Mystery and Thrillers', 'Asian Fusion', 'Bass', 'Non-Veg', 'Running Training', 'Video Games', 'Sculpture', 'Role-Playing Games (RPGs)', 'Mountain Climbing', 'Painting', 'Tennis', 'Fantasy', 'Ballroom Dancing', 'Environmental Conservation', 'Science Fiction', 'Trail Hiking', 'Hip-Hop Dance', 'Adventure Travel', 'Documentaries', 'Pottery'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Arnav Reddy', 'gender': 'male', 'interests': ['Asian Fusion', 'Bass', 'Mountain Climbing', 'Soccer', 'Running Training', 'French Cuisine', 'Road Trips', 'Non-Fiction', 'Disaster Relief', 'Environmental Conservation', 'Acoustic', 'Mystery and Thrillers', 'Role-Playing Games (RPGs)', 'Foodie', 'Pottery', 'Youth Mentorship', 'Homeless Shelter Support', 'Gourmet Cooking', 'Fantasy', 'Salsa Dancing'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Vivaan Chopra', 'gender': 'male', 'interests': ['Fiction Novels', 'Card Games', 'Swing Dance', 'Weightlifting', 'Bass', 'Solo Travel', 'Adventure Travel', 'Action Movies', 'Electric', 'Homeless Shelter Support', 'Hip-Hop Dance', 'Environmental Conservation', 'Yoga', 'Role-Playing Games (RPGs)', 'Trail Hiking', 'Science Fiction', 'Non-Smoker', 'French Cuisine', 'CrossFit', 'Italian Cuisine'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Rajat Kapoor', 'gender': 'male', 'interests': ['Swimming', 'Painting', 'Golf', 'Non-Fiction', 'French Cuisine', 'Board Games', 'Mobile Games', 'Running Training', 'Basketball', 'Yoga', 'Digital Art', 'Asian Fusion', 'Mystery and Thrillers', 'Disaster Relief', 'Weightlifting', 'Swing Dance', 'Ballroom Dancing', 'Action Movies', 'Mountain Climbing', 'Ballet'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Kabir Rao', 'gender': 'male', 'interests': ['French Cuisine', 'Photography', 'Basketball', 'Soccer', 'Acoustic', 'Ballet', 'Italian Cuisine', 'Documentaries', 'Mountain Climbing', 'Action Movies', 'Fiction Novels', 'Environmental Conservation', 'Non-Veg', 'Science Fiction', 'Disaster Relief', 'Nature Walks', 'Fantasy', 'Foodie', 'Electric', 'Baking Pastries'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Virat Mishra', 'gender': 'male', 'interests': ['Youth Mentorship', 'Fantasy', 'Basketball', 'Card Games', 'Mountain Climbing', 'Role-Playing Games (RPGs)', 'Trail Hiking', 'CrossFit', 'Tennis', 'Documentaries', 'Swimming', 'Swing Dance', 'Fingerstyle', 'Ballroom Dancing', 'Cultural Exploration', 'Backpacking', 'Pottery', 'Action Movies', 'Classical', 'Romantic Comedies'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Varun Khanna', 'gender': 'male', 'interests': ['Road Trips', 'Acoustic', 'Swing Dance', 'Environmental Conservation', 'Cultural Exploration', 'Trail Hiking', 'Italian Cuisine', 'Pottery', 'Bass', 'Salsa Dancing', 'Gourmet Cooking', 'Fingerstyle', 'Youth Mentorship', 'Sci-Fi Series', 'French Cuisine', 'Fiction Novels', 'Non-Fiction', 'Solo Travel', 'Fantasy', 'Mobile Games'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Anshul Malhotra', 'gender': 'male', 'interests': ['Mountain Climbing', 'Photography', 'Fantasy', 'Backpacking', 'Yoga', 'Board Games', 'Ballroom Dancing', 'Electric', 'Swimming', 'Video Games', 'Non-Veg', 'Baking Pastries', 'Non-Fiction', 'Asian Fusion', 'Trail Hiking', 'Adventure', 'Classical', 'Action Movies', 'Foodie', 'Romantic Comedies'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Pranav Yadav', 'gender': 'male', 'interests': ['Foodie', 'Running Training', 'Painting', 'Role-Playing Games (RPGs)', 'Weightlifting', 'Youth Mentorship', 'Trail Hiking', 'Adventure Travel', 'Acoustic', 'Cultural Exploration', 'Non-Smoker', 'Fiction Novels', 'Basketball', 'Fantasy', 'Adventure', 'Environmental Conservation', 'Bass', 'Animal Shelter Volunteering', 'Tennis', 'Pilates'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Pranav Yadav', 'gender': 'male', 'interests': ['Fiction Novels', 'Pilates', 'Road Trips', 'Swimming', 'Sci-Fi Series', 'Non-Fiction', 'French Cuisine', 'Salsa Dancing', 'Gourmet Cooking', 'Foodie', 'Painting', 'Yoga', 'Homeless Shelter Support', 'Fantasy', 'Day Hikes', 'Adventure', 'Non-Smoker', 'Non-Veg', 'Swing Dance', 'Video Games'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Rohit Thakur', 'gender': 'male', 'interests': ['CrossFit', 'Fingerstyle', 'Basketball', 'Solo Travel', 'Non-Fiction', 'Digital Art', 'Day Hikes', 'Card Games', 'Swimming', 'Animal Shelter Volunteering', 'Golf', 'Sci-Fi Series', 'Yoga', 'Documentaries', 'Hip-Hop Dance', 'Adventure', 'Mountain Climbing', 'Cultural Exploration', 'Mobile Games', 'Homeless Shelter Support'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Siddharth Verma', 'gender': 'male', 'interests': ['Non-Smoker', 'Pilates', 'Homeless Shelter Support', 'Swing Dance', 'Classic Films', 'Sci-Fi Series', 'Acoustic', 'Card Games', 'Salsa Dancing', 'Classical', 'Adventure Travel', 'Environmental Conservation', 'Swimming', 'Tennis', 'Gourmet Cooking', 'Fantasy', 'Soccer', 'Backpacking', 'Non-Veg', 'Documentaries'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Varun Khanna', 'gender': 'male', 'interests': ['Adventure Travel', 'Gourmet Cooking', 'Ballroom Dancing', 'Acoustic', 'Non-Fiction', 'Bass', 'Mobile Games', 'Romantic Comedies', 'Running Training', 'Swing Dance', 'Italian Cuisine', 'Fingerstyle', 'Painting', 'Environmental Conservation', 'Tennis', 'Basketball', 'Asian Fusion', 'Golf', 'Yoga', 'Pottery'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Siddharth Verma', 'gender': 'male', 'interests': ['Role-Playing Games (RPGs)', 'Fantasy', 'Pilates', 'Action Movies', 'Digital Art', 'Gourmet Cooking', 'Board Games', 'Non-Veg', 'Homeless Shelter Support', 'Animal Shelter Volunteering', 'Solo Travel', 'Adventure Travel', 'Fingerstyle', 'Acoustic', 'Running Training', 'Mobile Games', 'Science Fiction', 'Trail Hiking', 'Electric', 'Sculpture'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' },
    { 'name': 'Nikhil Aggarwal', 'gender': 'male', 'interests': ['Environmental Conservation', 'Mobile Games', 'Hip-Hop Dance', 'Golf', 'Mountain Climbing', 'Non-Smoker', 'Photography', 'Backpacking', 'Yoga', 'Action Movies', 'Mystery and Thrillers', 'Gourmet Cooking', 'Adventure Travel', 'Ballroom Dancing', 'Non-Veg', 'Swing Dance', 'CrossFit', 'Adventure', 'Acoustic', 'Swimming'], 'instagram': 'https://www.instagram.com/', 'relationshipStatus': 'Single' }


];



function matchUsers() {
    var form = document.getElementById("registrationForm");
    var resultDiv = document.getElementById("result");


    var name = form.name.value;
    var gender = form.gender.value;
    var selectedInterests = Array.from(form.querySelectorAll('input[type=checkbox]:checked')).map(input => input.value);

    var oppositeGenderUsers = usersData.filter(user => user.gender !== gender);

    var matchingResults = oppositeGenderUsers.map(user => {
        var commonInterests = user.interests.filter(interest => selectedInterests.includes(interest));
        var matchingPercentage = (commonInterests.length / selectedInterests.length) * 99.99 ;
        return {
            name: user.name,
            instagram: user.instagram,
            matchingPercentage: matchingPercentage,
            relationshipStatus: user.relationshipStatus
        };
    });

    var filteredResults = matchingResults.filter(result => result.matchingPercentage > 0);

    var resultWindow = window.open('', '_blank');

    if (filteredResults.length > 0) {
        filteredResults.forEach(result => {
            resultWindow.document.write("<p style='font-size: 20px; background-color: red; border: 1px solid white; padding: 5px; margin: 50px;'>" + result.name + " (Match: " + result.matchingPercentage.toFixed(2) + "%) - Relationship Status: " + user.relationshipStatus + " - Open Profile: <a href='https://www.instagram.com/" + result.instagram + "' target='_blank'>" + result.instagram + "</a></p>");

        });
    } else {
        resultWindow.document.write("<p>No matching users found.</p>");
    }

}
